/**
 * ojs.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The OjsCreateSubmissionRequest model module.
 * @module model/OjsCreateSubmissionRequest
 * @version version not set
 */
class OjsCreateSubmissionRequest {
    /**
     * Constructs a new <code>OjsCreateSubmissionRequest</code>.
     * @alias module:model/OjsCreateSubmissionRequest
     */
    constructor() { 
        
        OjsCreateSubmissionRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>OjsCreateSubmissionRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OjsCreateSubmissionRequest} obj Optional instance to populate.
     * @return {module:model/OjsCreateSubmissionRequest} The populated <code>OjsCreateSubmissionRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OjsCreateSubmissionRequest();

            if (data.hasOwnProperty('ofProblemId')) {
                obj['ofProblemId'] = ApiClient.convertToType(data['ofProblemId'], 'String');
            }
            if (data.hasOwnProperty('content')) {
                obj['content'] = ApiClient.convertToType(data['content'], 'String');
            }
            if (data.hasOwnProperty('language')) {
                obj['language'] = ApiClient.convertToType(data['language'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>OjsCreateSubmissionRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>OjsCreateSubmissionRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['ofProblemId'] && !(typeof data['ofProblemId'] === 'string' || data['ofProblemId'] instanceof String)) {
            throw new Error("Expected the field `ofProblemId` to be a primitive type in the JSON string but got " + data['ofProblemId']);
        }
        // ensure the json data is a string
        if (data['content'] && !(typeof data['content'] === 'string' || data['content'] instanceof String)) {
            throw new Error("Expected the field `content` to be a primitive type in the JSON string but got " + data['content']);
        }
        // ensure the json data is a string
        if (data['language'] && !(typeof data['language'] === 'string' || data['language'] instanceof String)) {
            throw new Error("Expected the field `language` to be a primitive type in the JSON string but got " + data['language']);
        }

        return true;
    }


}



/**
 * @member {String} ofProblemId
 */
OjsCreateSubmissionRequest.prototype['ofProblemId'] = undefined;

/**
 * @member {String} content
 */
OjsCreateSubmissionRequest.prototype['content'] = undefined;

/**
 * @member {String} language
 */
OjsCreateSubmissionRequest.prototype['language'] = undefined;






export default OjsCreateSubmissionRequest;

