/**
 * ojs.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import OjsSubmission from './OjsSubmission';

/**
 * The OjsCreateSubmissionResponse model module.
 * @module model/OjsCreateSubmissionResponse
 * @version version not set
 */
class OjsCreateSubmissionResponse {
    /**
     * Constructs a new <code>OjsCreateSubmissionResponse</code>.
     * @alias module:model/OjsCreateSubmissionResponse
     */
    constructor() { 
        
        OjsCreateSubmissionResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>OjsCreateSubmissionResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OjsCreateSubmissionResponse} obj Optional instance to populate.
     * @return {module:model/OjsCreateSubmissionResponse} The populated <code>OjsCreateSubmissionResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OjsCreateSubmissionResponse();

            if (data.hasOwnProperty('submission')) {
                obj['submission'] = OjsSubmission.constructFromObject(data['submission']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>OjsCreateSubmissionResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>OjsCreateSubmissionResponse</code>.
     */
    static validateJSON(data) {
        // validate the optional field `submission`
        if (data['submission']) { // data not null
          OjsSubmission.validateJSON(data['submission']);
        }

        return true;
    }


}



/**
 * @member {module:model/OjsSubmission} submission
 */
OjsCreateSubmissionResponse.prototype['submission'] = undefined;






export default OjsCreateSubmissionResponse;

