/**
 * ojs.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import OjsTestCase from './OjsTestCase';

/**
 * The OjsCreateTestCaseResponse model module.
 * @module model/OjsCreateTestCaseResponse
 * @version version not set
 */
class OjsCreateTestCaseResponse {
    /**
     * Constructs a new <code>OjsCreateTestCaseResponse</code>.
     * @alias module:model/OjsCreateTestCaseResponse
     */
    constructor() { 
        
        OjsCreateTestCaseResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>OjsCreateTestCaseResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OjsCreateTestCaseResponse} obj Optional instance to populate.
     * @return {module:model/OjsCreateTestCaseResponse} The populated <code>OjsCreateTestCaseResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OjsCreateTestCaseResponse();

            if (data.hasOwnProperty('testCase')) {
                obj['testCase'] = OjsTestCase.constructFromObject(data['testCase']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>OjsCreateTestCaseResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>OjsCreateTestCaseResponse</code>.
     */
    static validateJSON(data) {
        // validate the optional field `testCase`
        if (data['testCase']) { // data not null
          OjsTestCase.validateJSON(data['testCase']);
        }

        return true;
    }


}



/**
 * @member {module:model/OjsTestCase} testCase
 */
OjsCreateTestCaseResponse.prototype['testCase'] = undefined;






export default OjsCreateTestCaseResponse;

