/**
 * ojs.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import OjsProblem from './OjsProblem';

/**
 * The OjsGetProblemListResponse model module.
 * @module model/OjsGetProblemListResponse
 * @version version not set
 */
class OjsGetProblemListResponse {
    /**
     * Constructs a new <code>OjsGetProblemListResponse</code>.
     * @alias module:model/OjsGetProblemListResponse
     */
    constructor() { 
        
        OjsGetProblemListResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>OjsGetProblemListResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OjsGetProblemListResponse} obj Optional instance to populate.
     * @return {module:model/OjsGetProblemListResponse} The populated <code>OjsGetProblemListResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OjsGetProblemListResponse();

            if (data.hasOwnProperty('problems')) {
                obj['problems'] = ApiClient.convertToType(data['problems'], [OjsProblem]);
            }
            if (data.hasOwnProperty('totalProblemCount')) {
                obj['totalProblemCount'] = ApiClient.convertToType(data['totalProblemCount'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>OjsGetProblemListResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>OjsGetProblemListResponse</code>.
     */
    static validateJSON(data) {
        if (data['problems']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['problems'])) {
                throw new Error("Expected the field `problems` to be an array in the JSON data but got " + data['problems']);
            }
            // validate the optional field `problems` (array)
            for (const item of data['problems']) {
                OjsProblem.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['totalProblemCount'] && !(typeof data['totalProblemCount'] === 'string' || data['totalProblemCount'] instanceof String)) {
            throw new Error("Expected the field `totalProblemCount` to be a primitive type in the JSON string but got " + data['totalProblemCount']);
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/OjsProblem>} problems
 */
OjsGetProblemListResponse.prototype['problems'] = undefined;

/**
 * @member {String} totalProblemCount
 */
OjsGetProblemListResponse.prototype['totalProblemCount'] = undefined;






export default OjsGetProblemListResponse;

