/**
 * ojs.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import OjsSubmission from './OjsSubmission';

/**
 * The OjsGetAccountProblemSubmissionListResponse model module.
 * @module model/OjsGetAccountProblemSubmissionListResponse
 * @version version not set
 */
class OjsGetAccountProblemSubmissionListResponse {
    /**
     * Constructs a new <code>OjsGetAccountProblemSubmissionListResponse</code>.
     * @alias module:model/OjsGetAccountProblemSubmissionListResponse
     */
    constructor() { 
        
        OjsGetAccountProblemSubmissionListResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>OjsGetAccountProblemSubmissionListResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OjsGetAccountProblemSubmissionListResponse} obj Optional instance to populate.
     * @return {module:model/OjsGetAccountProblemSubmissionListResponse} The populated <code>OjsGetAccountProblemSubmissionListResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OjsGetAccountProblemSubmissionListResponse();

            if (data.hasOwnProperty('submissions')) {
                obj['submissions'] = ApiClient.convertToType(data['submissions'], [OjsSubmission]);
            }
            if (data.hasOwnProperty('totalSubmissionsCount')) {
                obj['totalSubmissionsCount'] = ApiClient.convertToType(data['totalSubmissionsCount'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>OjsGetAccountProblemSubmissionListResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>OjsGetAccountProblemSubmissionListResponse</code>.
     */
    static validateJSON(data) {
        if (data['submissions']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['submissions'])) {
                throw new Error("Expected the field `submissions` to be an array in the JSON data but got " + data['submissions']);
            }
            // validate the optional field `submissions` (array)
            for (const item of data['submissions']) {
                OjsSubmission.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['totalSubmissionsCount'] && !(typeof data['totalSubmissionsCount'] === 'string' || data['totalSubmissionsCount'] instanceof String)) {
            throw new Error("Expected the field `totalSubmissionsCount` to be a primitive type in the JSON string but got " + data['totalSubmissionsCount']);
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/OjsSubmission>} submissions
 */
OjsGetAccountProblemSubmissionListResponse.prototype['submissions'] = undefined;

/**
 * @member {String} totalSubmissionsCount
 */
OjsGetAccountProblemSubmissionListResponse.prototype['totalSubmissionsCount'] = undefined;






export default OjsGetAccountProblemSubmissionListResponse;

