/**
 * ojs.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The OjsProblem model module.
 * @module model/OjsProblem
 * @version version not set
 */
class OjsProblem {
    /**
     * Constructs a new <code>OjsProblem</code>.
     * @alias module:model/OjsProblem
     */
    constructor() { 
        
        OjsProblem.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>OjsProblem</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OjsProblem} obj Optional instance to populate.
     * @return {module:model/OjsProblem} The populated <code>OjsProblem</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OjsProblem();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('displayName')) {
                obj['displayName'] = ApiClient.convertToType(data['displayName'], 'String');
            }
            if (data.hasOwnProperty('authorId')) {
                obj['authorId'] = ApiClient.convertToType(data['authorId'], 'String');
            }
            if (data.hasOwnProperty('authorName')) {
                obj['authorName'] = ApiClient.convertToType(data['authorName'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('timeLimit')) {
                obj['timeLimit'] = ApiClient.convertToType(data['timeLimit'], 'String');
            }
            if (data.hasOwnProperty('memoryLimit')) {
                obj['memoryLimit'] = ApiClient.convertToType(data['memoryLimit'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>OjsProblem</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>OjsProblem</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['displayName'] && !(typeof data['displayName'] === 'string' || data['displayName'] instanceof String)) {
            throw new Error("Expected the field `displayName` to be a primitive type in the JSON string but got " + data['displayName']);
        }
        // ensure the json data is a string
        if (data['authorId'] && !(typeof data['authorId'] === 'string' || data['authorId'] instanceof String)) {
            throw new Error("Expected the field `authorId` to be a primitive type in the JSON string but got " + data['authorId']);
        }
        // ensure the json data is a string
        if (data['authorName'] && !(typeof data['authorName'] === 'string' || data['authorName'] instanceof String)) {
            throw new Error("Expected the field `authorName` to be a primitive type in the JSON string but got " + data['authorName']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['timeLimit'] && !(typeof data['timeLimit'] === 'string' || data['timeLimit'] instanceof String)) {
            throw new Error("Expected the field `timeLimit` to be a primitive type in the JSON string but got " + data['timeLimit']);
        }
        // ensure the json data is a string
        if (data['memoryLimit'] && !(typeof data['memoryLimit'] === 'string' || data['memoryLimit'] instanceof String)) {
            throw new Error("Expected the field `memoryLimit` to be a primitive type in the JSON string but got " + data['memoryLimit']);
        }

        return true;
    }


}



/**
 * @member {String} id
 */
OjsProblem.prototype['id'] = undefined;

/**
 * @member {String} displayName
 */
OjsProblem.prototype['displayName'] = undefined;

/**
 * @member {String} authorId
 */
OjsProblem.prototype['authorId'] = undefined;

/**
 * @member {String} authorName
 */
OjsProblem.prototype['authorName'] = undefined;

/**
 * @member {String} description
 */
OjsProblem.prototype['description'] = undefined;

/**
 * @member {String} timeLimit
 */
OjsProblem.prototype['timeLimit'] = undefined;

/**
 * @member {String} memoryLimit
 */
OjsProblem.prototype['memoryLimit'] = undefined;






export default OjsProblem;

