/**
 * ojs.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class OjsRole.
* @enum {}
* @readonly
*/
export default class OjsRole {
    
        /**
         * value: "UndefinedRole"
         * @const
         */
        "UndefinedRole" = "UndefinedRole";

    
        /**
         * value: "Admin"
         * @const
         */
        "Admin" = "Admin";

    
        /**
         * value: "Contester"
         * @const
         */
        "Contester" = "Contester";

    
        /**
         * value: "ProblemSetter"
         * @const
         */
        "ProblemSetter" = "ProblemSetter";

    

    /**
    * Returns a <code>OjsRole</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/OjsRole} The enum <code>OjsRole</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

