/**
 * ojs.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The OjsServiceUpdateProblemBody model module.
 * @module model/OjsServiceUpdateProblemBody
 * @version version not set
 */
class OjsServiceUpdateProblemBody {
    /**
     * Constructs a new <code>OjsServiceUpdateProblemBody</code>.
     * @alias module:model/OjsServiceUpdateProblemBody
     */
    constructor() { 
        
        OjsServiceUpdateProblemBody.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>OjsServiceUpdateProblemBody</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OjsServiceUpdateProblemBody} obj Optional instance to populate.
     * @return {module:model/OjsServiceUpdateProblemBody} The populated <code>OjsServiceUpdateProblemBody</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OjsServiceUpdateProblemBody();

            if (data.hasOwnProperty('displayName')) {
                obj['displayName'] = ApiClient.convertToType(data['displayName'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('timeLimit')) {
                obj['timeLimit'] = ApiClient.convertToType(data['timeLimit'], 'String');
            }
            if (data.hasOwnProperty('memoryLimit')) {
                obj['memoryLimit'] = ApiClient.convertToType(data['memoryLimit'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>OjsServiceUpdateProblemBody</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>OjsServiceUpdateProblemBody</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['displayName'] && !(typeof data['displayName'] === 'string' || data['displayName'] instanceof String)) {
            throw new Error("Expected the field `displayName` to be a primitive type in the JSON string but got " + data['displayName']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['timeLimit'] && !(typeof data['timeLimit'] === 'string' || data['timeLimit'] instanceof String)) {
            throw new Error("Expected the field `timeLimit` to be a primitive type in the JSON string but got " + data['timeLimit']);
        }
        // ensure the json data is a string
        if (data['memoryLimit'] && !(typeof data['memoryLimit'] === 'string' || data['memoryLimit'] instanceof String)) {
            throw new Error("Expected the field `memoryLimit` to be a primitive type in the JSON string but got " + data['memoryLimit']);
        }

        return true;
    }


}



/**
 * @member {String} displayName
 */
OjsServiceUpdateProblemBody.prototype['displayName'] = undefined;

/**
 * @member {String} description
 */
OjsServiceUpdateProblemBody.prototype['description'] = undefined;

/**
 * @member {String} timeLimit
 */
OjsServiceUpdateProblemBody.prototype['timeLimit'] = undefined;

/**
 * @member {String} memoryLimit
 */
OjsServiceUpdateProblemBody.prototype['memoryLimit'] = undefined;






export default OjsServiceUpdateProblemBody;

