/**
 * ojs.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import OjsSubmissionResult from './OjsSubmissionResult';
import OjsSubmissionStatus from './OjsSubmissionStatus';

/**
 * The OjsSubmission model module.
 * @module model/OjsSubmission
 * @version version not set
 */
class OjsSubmission {
    /**
     * Constructs a new <code>OjsSubmission</code>.
     * @alias module:model/OjsSubmission
     */
    constructor() { 
        
        OjsSubmission.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>OjsSubmission</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OjsSubmission} obj Optional instance to populate.
     * @return {module:model/OjsSubmission} The populated <code>OjsSubmission</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OjsSubmission();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('ofProblemId')) {
                obj['ofProblemId'] = ApiClient.convertToType(data['ofProblemId'], 'String');
            }
            if (data.hasOwnProperty('authorId')) {
                obj['authorId'] = ApiClient.convertToType(data['authorId'], 'String');
            }
            if (data.hasOwnProperty('content')) {
                obj['content'] = ApiClient.convertToType(data['content'], 'String');
            }
            if (data.hasOwnProperty('language')) {
                obj['language'] = ApiClient.convertToType(data['language'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = OjsSubmissionStatus.constructFromObject(data['status']);
            }
            if (data.hasOwnProperty('result')) {
                obj['result'] = OjsSubmissionResult.constructFromObject(data['result']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>OjsSubmission</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>OjsSubmission</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['ofProblemId'] && !(typeof data['ofProblemId'] === 'string' || data['ofProblemId'] instanceof String)) {
            throw new Error("Expected the field `ofProblemId` to be a primitive type in the JSON string but got " + data['ofProblemId']);
        }
        // ensure the json data is a string
        if (data['authorId'] && !(typeof data['authorId'] === 'string' || data['authorId'] instanceof String)) {
            throw new Error("Expected the field `authorId` to be a primitive type in the JSON string but got " + data['authorId']);
        }
        // ensure the json data is a string
        if (data['content'] && !(typeof data['content'] === 'string' || data['content'] instanceof String)) {
            throw new Error("Expected the field `content` to be a primitive type in the JSON string but got " + data['content']);
        }
        // ensure the json data is a string
        if (data['language'] && !(typeof data['language'] === 'string' || data['language'] instanceof String)) {
            throw new Error("Expected the field `language` to be a primitive type in the JSON string but got " + data['language']);
        }

        return true;
    }


}



/**
 * @member {String} id
 */
OjsSubmission.prototype['id'] = undefined;

/**
 * @member {String} ofProblemId
 */
OjsSubmission.prototype['ofProblemId'] = undefined;

/**
 * @member {String} authorId
 */
OjsSubmission.prototype['authorId'] = undefined;

/**
 * @member {String} content
 */
OjsSubmission.prototype['content'] = undefined;

/**
 * @member {String} language
 */
OjsSubmission.prototype['language'] = undefined;

/**
 * @member {module:model/OjsSubmissionStatus} status
 */
OjsSubmission.prototype['status'] = undefined;

/**
 * @member {module:model/OjsSubmissionResult} result
 */
OjsSubmission.prototype['result'] = undefined;






export default OjsSubmission;

