/**
 * ojs.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class OjsSubmissionResult.
* @enum {}
* @readonly
*/
export default class OjsSubmissionResult {
    
        /**
         * value: "UndefinedResult"
         * @const
         */
        "UndefinedResult" = "UndefinedResult";

    
        /**
         * value: "OK"
         * @const
         */
        "OK" = "OK";

    
        /**
         * value: "CompileError"
         * @const
         */
        "CompileError" = "CompileError";

    
        /**
         * value: "RuntimeError"
         * @const
         */
        "RuntimeError" = "RuntimeError";

    
        /**
         * value: "TimeLimitExceeded"
         * @const
         */
        "TimeLimitExceeded" = "TimeLimitExceeded";

    
        /**
         * value: "MemoryLimitExceeded"
         * @const
         */
        "MemoryLimitExceeded" = "MemoryLimitExceeded";

    
        /**
         * value: "WrongAnswer"
         * @const
         */
        "WrongAnswer" = "WrongAnswer";

    
        /**
         * value: "UnsupportedLanguage"
         * @const
         */
        "UnsupportedLanguage" = "UnsupportedLanguage";

    

    /**
    * Returns a <code>OjsSubmissionResult</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/OjsSubmissionResult} The enum <code>OjsSubmissionResult</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

