/**
 * ojs.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import OjsProblem from './OjsProblem';

/**
 * The OjsUpdateProblemResponse model module.
 * @module model/OjsUpdateProblemResponse
 * @version version not set
 */
class OjsUpdateProblemResponse {
    /**
     * Constructs a new <code>OjsUpdateProblemResponse</code>.
     * @alias module:model/OjsUpdateProblemResponse
     */
    constructor() { 
        
        OjsUpdateProblemResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>OjsUpdateProblemResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OjsUpdateProblemResponse} obj Optional instance to populate.
     * @return {module:model/OjsUpdateProblemResponse} The populated <code>OjsUpdateProblemResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OjsUpdateProblemResponse();

            if (data.hasOwnProperty('problem')) {
                obj['problem'] = OjsProblem.constructFromObject(data['problem']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>OjsUpdateProblemResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>OjsUpdateProblemResponse</code>.
     */
    static validateJSON(data) {
        // validate the optional field `problem`
        if (data['problem']) { // data not null
          OjsProblem.validateJSON(data['problem']);
        }

        return true;
    }


}



/**
 * @member {module:model/OjsProblem} problem
 */
OjsUpdateProblemResponse.prototype['problem'] = undefined;






export default OjsUpdateProblemResponse;

