/**
 * ojs.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OjsProto);
  }
}(this, function(expect, OjsProto) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OjsProto.OjsServiceApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('OjsServiceApi', function() {
    describe('ojsServiceCreateAccount', function() {
      it('should call ojsServiceCreateAccount successfully', function(done) {
        //uncomment below and update the code to test ojsServiceCreateAccount
        //instance.ojsServiceCreateAccount(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('ojsServiceCreateProblem', function() {
      it('should call ojsServiceCreateProblem successfully', function(done) {
        //uncomment below and update the code to test ojsServiceCreateProblem
        //instance.ojsServiceCreateProblem(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('ojsServiceCreateSession', function() {
      it('should call ojsServiceCreateSession successfully', function(done) {
        //uncomment below and update the code to test ojsServiceCreateSession
        //instance.ojsServiceCreateSession(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('ojsServiceCreateSubmission', function() {
      it('should call ojsServiceCreateSubmission successfully', function(done) {
        //uncomment below and update the code to test ojsServiceCreateSubmission
        //instance.ojsServiceCreateSubmission(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('ojsServiceCreateTestCase', function() {
      it('should call ojsServiceCreateTestCase successfully', function(done) {
        //uncomment below and update the code to test ojsServiceCreateTestCase
        //instance.ojsServiceCreateTestCase(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('ojsServiceDeleteProblem', function() {
      it('should call ojsServiceDeleteProblem successfully', function(done) {
        //uncomment below and update the code to test ojsServiceDeleteProblem
        //instance.ojsServiceDeleteProblem(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('ojsServiceDeleteSession', function() {
      it('should call ojsServiceDeleteSession successfully', function(done) {
        //uncomment below and update the code to test ojsServiceDeleteSession
        //instance.ojsServiceDeleteSession(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('ojsServiceDeleteTestCase', function() {
      it('should call ojsServiceDeleteTestCase successfully', function(done) {
        //uncomment below and update the code to test ojsServiceDeleteTestCase
        //instance.ojsServiceDeleteTestCase(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('ojsServiceGetAccount', function() {
      it('should call ojsServiceGetAccount successfully', function(done) {
        //uncomment below and update the code to test ojsServiceGetAccount
        //instance.ojsServiceGetAccount(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('ojsServiceGetAccountProblemSubmissionList', function() {
      it('should call ojsServiceGetAccountProblemSubmissionList successfully', function(done) {
        //uncomment below and update the code to test ojsServiceGetAccountProblemSubmissionList
        //instance.ojsServiceGetAccountProblemSubmissionList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('ojsServiceGetProblem', function() {
      it('should call ojsServiceGetProblem successfully', function(done) {
        //uncomment below and update the code to test ojsServiceGetProblem
        //instance.ojsServiceGetProblem(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('ojsServiceGetProblemList', function() {
      it('should call ojsServiceGetProblemList successfully', function(done) {
        //uncomment below and update the code to test ojsServiceGetProblemList
        //instance.ojsServiceGetProblemList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('ojsServiceGetProblemSubmissionList', function() {
      it('should call ojsServiceGetProblemSubmissionList successfully', function(done) {
        //uncomment below and update the code to test ojsServiceGetProblemSubmissionList
        //instance.ojsServiceGetProblemSubmissionList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('ojsServiceGetProblemTestCaseList', function() {
      it('should call ojsServiceGetProblemTestCaseList successfully', function(done) {
        //uncomment below and update the code to test ojsServiceGetProblemTestCaseList
        //instance.ojsServiceGetProblemTestCaseList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('ojsServiceGetServerInfo', function() {
      it('should call ojsServiceGetServerInfo successfully', function(done) {
        //uncomment below and update the code to test ojsServiceGetServerInfo
        //instance.ojsServiceGetServerInfo(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('ojsServiceGetSubmission', function() {
      it('should call ojsServiceGetSubmission successfully', function(done) {
        //uncomment below and update the code to test ojsServiceGetSubmission
        //instance.ojsServiceGetSubmission(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('ojsServiceGetSubmissionList', function() {
      it('should call ojsServiceGetSubmissionList successfully', function(done) {
        //uncomment below and update the code to test ojsServiceGetSubmissionList
        //instance.ojsServiceGetSubmissionList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('ojsServiceGetTestCase', function() {
      it('should call ojsServiceGetTestCase successfully', function(done) {
        //uncomment below and update the code to test ojsServiceGetTestCase
        //instance.ojsServiceGetTestCase(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('ojsServiceUpdateProblem', function() {
      it('should call ojsServiceUpdateProblem successfully', function(done) {
        //uncomment below and update the code to test ojsServiceUpdateProblem
        //instance.ojsServiceUpdateProblem(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('ojsServiceUpdateTestCase', function() {
      it('should call ojsServiceUpdateTestCase successfully', function(done) {
        //uncomment below and update the code to test ojsServiceUpdateTestCase
        //instance.ojsServiceUpdateTestCase(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
