/**
 * ojs.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OjsProto);
  }
}(this, function(expect, OjsProto) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OjsProto.OjsCreateProblemRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('OjsCreateProblemRequest', function() {
    it('should create an instance of OjsCreateProblemRequest', function() {
      // uncomment below and update the code to test OjsCreateProblemRequest
      //var instance = new OjsProto.OjsCreateProblemRequest();
      //expect(instance).to.be.a(OjsProto.OjsCreateProblemRequest);
    });

    it('should have the property displayName (base name: "displayName")', function() {
      // uncomment below and update the code to test the property displayName
      //var instance = new OjsProto.OjsCreateProblemRequest();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new OjsProto.OjsCreateProblemRequest();
      //expect(instance).to.be();
    });

    it('should have the property timeLimit (base name: "timeLimit")', function() {
      // uncomment below and update the code to test the property timeLimit
      //var instance = new OjsProto.OjsCreateProblemRequest();
      //expect(instance).to.be();
    });

    it('should have the property memoryLimit (base name: "memoryLimit")', function() {
      // uncomment below and update the code to test the property memoryLimit
      //var instance = new OjsProto.OjsCreateProblemRequest();
      //expect(instance).to.be();
    });

  });

}));
