/**
 * ojs.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import OjsAccount from './model/OjsAccount';
import OjsCreateAccountRequest from './model/OjsCreateAccountRequest';
import OjsCreateAccountResponse from './model/OjsCreateAccountResponse';
import OjsCreateProblemRequest from './model/OjsCreateProblemRequest';
import OjsCreateProblemResponse from './model/OjsCreateProblemResponse';
import OjsCreateSessionRequest from './model/OjsCreateSessionRequest';
import OjsCreateSessionResponse from './model/OjsCreateSessionResponse';
import OjsCreateSubmissionRequest from './model/OjsCreateSubmissionRequest';
import OjsCreateSubmissionResponse from './model/OjsCreateSubmissionResponse';
import OjsCreateTestCaseRequest from './model/OjsCreateTestCaseRequest';
import OjsCreateTestCaseResponse from './model/OjsCreateTestCaseResponse';
import OjsGetAccountProblemSubmissionListResponse from './model/OjsGetAccountProblemSubmissionListResponse';
import OjsGetAccountResponse from './model/OjsGetAccountResponse';
import OjsGetProblemListResponse from './model/OjsGetProblemListResponse';
import OjsGetProblemResponse from './model/OjsGetProblemResponse';
import OjsGetProblemSubmissionListResponse from './model/OjsGetProblemSubmissionListResponse';
import OjsGetProblemTestCaseListResponse from './model/OjsGetProblemTestCaseListResponse';
import OjsGetSubmissionListResponse from './model/OjsGetSubmissionListResponse';
import OjsGetSubmissionResponse from './model/OjsGetSubmissionResponse';
import OjsGetTestCaseResponse from './model/OjsGetTestCaseResponse';
import OjsProblem from './model/OjsProblem';
import OjsRole from './model/OjsRole';
import OjsServiceUpdateProblemBody from './model/OjsServiceUpdateProblemBody';
import OjsServiceUpdateTestCaseBody from './model/OjsServiceUpdateTestCaseBody';
import OjsSubmission from './model/OjsSubmission';
import OjsSubmissionResult from './model/OjsSubmissionResult';
import OjsSubmissionStatus from './model/OjsSubmissionStatus';
import OjsTestCase from './model/OjsTestCase';
import OjsUpdateProblemResponse from './model/OjsUpdateProblemResponse';
import OjsUpdateTestCaseResponse from './model/OjsUpdateTestCaseResponse';
import ProtobufAny from './model/ProtobufAny';
import RpcStatus from './model/RpcStatus';
import OjsServiceApi from './api/OjsServiceApi';


/**
* JS API client generated by OpenAPI Generator.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var OjsProto = require('index'); // See note below*.
* var xxxSvc = new OjsProto.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new OjsProto.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new OjsProto.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new OjsProto.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version version not set
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The OjsAccount model constructor.
     * @property {module:model/OjsAccount}
     */
    OjsAccount,

    /**
     * The OjsCreateAccountRequest model constructor.
     * @property {module:model/OjsCreateAccountRequest}
     */
    OjsCreateAccountRequest,

    /**
     * The OjsCreateAccountResponse model constructor.
     * @property {module:model/OjsCreateAccountResponse}
     */
    OjsCreateAccountResponse,

    /**
     * The OjsCreateProblemRequest model constructor.
     * @property {module:model/OjsCreateProblemRequest}
     */
    OjsCreateProblemRequest,

    /**
     * The OjsCreateProblemResponse model constructor.
     * @property {module:model/OjsCreateProblemResponse}
     */
    OjsCreateProblemResponse,

    /**
     * The OjsCreateSessionRequest model constructor.
     * @property {module:model/OjsCreateSessionRequest}
     */
    OjsCreateSessionRequest,

    /**
     * The OjsCreateSessionResponse model constructor.
     * @property {module:model/OjsCreateSessionResponse}
     */
    OjsCreateSessionResponse,

    /**
     * The OjsCreateSubmissionRequest model constructor.
     * @property {module:model/OjsCreateSubmissionRequest}
     */
    OjsCreateSubmissionRequest,

    /**
     * The OjsCreateSubmissionResponse model constructor.
     * @property {module:model/OjsCreateSubmissionResponse}
     */
    OjsCreateSubmissionResponse,

    /**
     * The OjsCreateTestCaseRequest model constructor.
     * @property {module:model/OjsCreateTestCaseRequest}
     */
    OjsCreateTestCaseRequest,

    /**
     * The OjsCreateTestCaseResponse model constructor.
     * @property {module:model/OjsCreateTestCaseResponse}
     */
    OjsCreateTestCaseResponse,

    /**
     * The OjsGetAccountProblemSubmissionListResponse model constructor.
     * @property {module:model/OjsGetAccountProblemSubmissionListResponse}
     */
    OjsGetAccountProblemSubmissionListResponse,

    /**
     * The OjsGetAccountResponse model constructor.
     * @property {module:model/OjsGetAccountResponse}
     */
    OjsGetAccountResponse,

    /**
     * The OjsGetProblemListResponse model constructor.
     * @property {module:model/OjsGetProblemListResponse}
     */
    OjsGetProblemListResponse,

    /**
     * The OjsGetProblemResponse model constructor.
     * @property {module:model/OjsGetProblemResponse}
     */
    OjsGetProblemResponse,

    /**
     * The OjsGetProblemSubmissionListResponse model constructor.
     * @property {module:model/OjsGetProblemSubmissionListResponse}
     */
    OjsGetProblemSubmissionListResponse,

    /**
     * The OjsGetProblemTestCaseListResponse model constructor.
     * @property {module:model/OjsGetProblemTestCaseListResponse}
     */
    OjsGetProblemTestCaseListResponse,

    /**
     * The OjsGetSubmissionListResponse model constructor.
     * @property {module:model/OjsGetSubmissionListResponse}
     */
    OjsGetSubmissionListResponse,

    /**
     * The OjsGetSubmissionResponse model constructor.
     * @property {module:model/OjsGetSubmissionResponse}
     */
    OjsGetSubmissionResponse,

    /**
     * The OjsGetTestCaseResponse model constructor.
     * @property {module:model/OjsGetTestCaseResponse}
     */
    OjsGetTestCaseResponse,

    /**
     * The OjsProblem model constructor.
     * @property {module:model/OjsProblem}
     */
    OjsProblem,

    /**
     * The OjsRole model constructor.
     * @property {module:model/OjsRole}
     */
    OjsRole,

    /**
     * The OjsServiceUpdateProblemBody model constructor.
     * @property {module:model/OjsServiceUpdateProblemBody}
     */
    OjsServiceUpdateProblemBody,

    /**
     * The OjsServiceUpdateTestCaseBody model constructor.
     * @property {module:model/OjsServiceUpdateTestCaseBody}
     */
    OjsServiceUpdateTestCaseBody,

    /**
     * The OjsSubmission model constructor.
     * @property {module:model/OjsSubmission}
     */
    OjsSubmission,

    /**
     * The OjsSubmissionResult model constructor.
     * @property {module:model/OjsSubmissionResult}
     */
    OjsSubmissionResult,

    /**
     * The OjsSubmissionStatus model constructor.
     * @property {module:model/OjsSubmissionStatus}
     */
    OjsSubmissionStatus,

    /**
     * The OjsTestCase model constructor.
     * @property {module:model/OjsTestCase}
     */
    OjsTestCase,

    /**
     * The OjsUpdateProblemResponse model constructor.
     * @property {module:model/OjsUpdateProblemResponse}
     */
    OjsUpdateProblemResponse,

    /**
     * The OjsUpdateTestCaseResponse model constructor.
     * @property {module:model/OjsUpdateTestCaseResponse}
     */
    OjsUpdateTestCaseResponse,

    /**
     * The ProtobufAny model constructor.
     * @property {module:model/ProtobufAny}
     */
    ProtobufAny,

    /**
     * The RpcStatus model constructor.
     * @property {module:model/RpcStatus}
     */
    RpcStatus,

    /**
    * The OjsServiceApi service constructor.
    * @property {module:api/OjsServiceApi}
    */
    OjsServiceApi
};
