auth:
  hash:
    cost: 4
  token:
    duration: 24h
    rs512_key_pair_bit_size: 2048
database:
  type: "mysql"
  host: "0.0.0.0"
  port: 3306
  username: "root"
  password: "secret"
  database: "ojs"
log:
  level: "debug" # [debug, info, warn, error, panic]
cache:
  type: "redis" # [redis, in-memory]
  addr: "0.0.0.0:6379"
  username: ""
  password: ""
  db: 0
grpc:
  address: "0.0.0.0:8080"
http:
  address: "0.0.0.0:8081"
mq:
  addresses: ["0.0.0.0:9092"]
  client_id: "1"
judge:
  languages:
    - value: c
      name: C
      compile:
        image: "docker.io/library/gcc:9.5.0-bullseye"
        cpus: 2
        memory: 1GiB
        timeout: 30s
        source_file_name: "main.c"
        program_file_name: "main.out"
        command_template: ["g++", "-o", "$PROGRAM", "$SOURCE"]
      execute:
        image: "docker.io/library/debian:bullseye-slim"
        cpus: 2
        memory: 1GiB
        timeout: 30s
        command_template: ["timeout", "--foreground", "$TIMEOUT", "$PROGRAM"]
    - value: cpp
      name: C++
      compile:
        image: "docker.io/library/gcc:9.5.0-bullseye"
        cpus: 2
        memory: 1GiB
        timeout: 30s
        source_file_name: "main.cpp"
        program_file_name: "main.out"
        command_template: ["g++", "-o", "$PROGRAM", "$SOURCE"]
      execute:
        image: "docker.io/library/debian:bullseye-slim"
        cpus: 2
        memory: 1GiB
        timeout: 30s
        command_template: ["timeout", "--foreground", "$TIMEOUT", "$PROGRAM"]
    - value: java
      name: Java
      compile:
        image: "docker.io/library/openjdk:22-jdk-slim-buster"
        cpus: 2
        memory: 1GiB
        timeout: 30s
        source_file_name: "Main.java"
        program_file_name: "Main.class"
        command_template: ["javac", "$SOURCE"]
      execute:
        image: "docker.io/library/openjdk:22-jdk-slim-buster"
        cpus: 2
        memory: 1GiB
        timeout: 30s
        command_template:
          ["timeout", "--foreground", "$TIMEOUT", "java", "Main"]
    - value: python
      name: Python 3
      execute:
        image: "docker.io/library/python:3.13-rc-slim"
        cpus: 2
        memory: 1GiB
        timeout: 30s
        command_template:
          ["timeout", "--foreground", "$TIMEOUT", "python3", "$PROGRAM"]
