version: "3.9"
services:
  redis:
    image: redis:7.2.4
    container_name: redis
    hostname: redis
    restart: always
    networks:
      - intranet
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 3s
      retries: 3

  mysql:
    image: mysql:8.3.0
    container_name: mysql
    hostname: mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: idm
    restart: always
    networks:
      - intranet
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 3s
      retries: 3

  zookeeper:
    image: "bitnami/zookeeper:3.8-debian-10"
    container_name: zookeeper
    hostname: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    restart: always
    networks:
      - intranet
    ports:
      - "2181:2181"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "2181"]
      timeout: 3s
      retries: 3

  kafka:
    image: "bitnami/kafka:3.1-debian-10"
    container_name: kafka
    hostname: kafka
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    restart: always
    ports:
      - "9092:9092"
    networks:
      - intranet

  minio:
    image: minio/minio:latest
    container_name: minio
    hostname: minio
    environment:
        - MINIO_ROOT_USER=root
        - MINIO_ROOT_PASSWORD=secret123
    command: server /data --address "0.0.0.0:9000" --console-address "0.0.0.0:9001"
    restart: always
    ports:
        - "9000:9000"
        - "9001:9001"
    networks:
      - intranet

networks:
  intranet: {}
